version: 2

models:
  - name: dim_listings_cleansed
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null
      - name: host_id
        tests:
        - not_null
        - relationships: # between listings and hosts
            to: ref('dim_hosts_cleansed')
            field: host_id
      - name: room_type
        tests:
         - accepted_values:
             values: ['Entire home/apt', # add different values to break it and get test location
                      'Private room',
                      'Shared room',
                      'Hotel room']
      - name: minimum_nights
        tests:
         - positive_value
